### ISSUE TITLE
Adding Wind Error to 5-3-wind-graph_create.R

### ISSUE THREAD

**Issue by grhyne** [grhyne/SWWA_Pressure#2]
While creating the wind graph (5-3 in Analysis), I ran into an error after the graph was created when trying to add the wind, as follows:
```{r}
> # Add wind
> grl <- graph_add_wind(grl,
+   pressure = pam$pressure,
+   filename = paste0("data/5_wind_graph/", gdl, "/", gdl, "_"),
+   thr_as = gpr$thr_as
+ )
[                                                  ] 0 / 460357 | sta = 0/6Error in ncvar_get_inner(ncid2use, varid2use, nc$var[[li]]$missval, addOffset,  : 
  Error: variable has 4 dims, but start has 3 entries.  They must match!
In addition: There were 18 warnings (use warnings() to see them)
```
The wind data was successfully downloaded, and 9 nc files are stored in the 5_wind_graph/CB594 folder. I am unsure of how to solve this

**Comment by Rafnuss** [comment]
Can you check again that you have the latest version of GeoPressureR 
This is the commit that solved should have solved this issue: https://github.com/Rafnuss/GeoPressureR/commit/37777b1d29be2a803ade8b688e3b6c17dd151f59

**Comment by grhyne** [comment]
I thought I had updated it before my session today, but apparently I hadn't. Problem solved, thanks
