### ISSUE TITLE
geopressureviz unequal row lengths

### ISSUE THREAD

**Issue by grhyne** [grhyne/SWWA_Pressure#3]
When trying to generate my geopressureviz with the shiny app, I recieve this error:
```{r}
> geopressureviz <- list(
+   pam_data = pam,
+   static_prob = static_prob,
+   static_prob_marginal = static_prob_marginal,
+   pressure_prob = pressure_prob,
+   #light_prob = light_prob,
+   pressure_timeserie = shortest_path_timeserie
+ )
> save(geopressureviz, file = "~/geopressureviz.RData")
> shiny::runApp(system.file("geopressureviz", package = "GeoPressureR"),
+   launch.browser = getOption("C:/Program Files/Google/Chrome/Application/chrome.exe")
+ )
 Error: length(pressure_timeserie) == nrow(sta) is not TRUE
```
Referring to unequal lengths of the combined objects. As you can see, I commented-out anything referring to the non-existent light data. The pressure timeseries should have the same length as the number of stationary locations, so I am unsure of how to solve this problem. I am wary of messing with too much under the hood of the timeserie, hence why I would rather ask first.

**Comment by Rafnuss** [comment]
Did you compute `pressure_timeserie` before updating GeoPressureR (same as previous issue). Check the length of `pressure_timeserie` and `pam$sta` (as well as all the others). It should be 10 stationary periods I think.

**Comment by grhyne** [comment]
Yes, I had to restart the pipeline which is what I should have done in the first place after updating the package. Thanks!
