### ISSUE TITLE
Pressure Observations Error

### ISSUE THREAD

**Issue by grhyne** [grhyne/SWWA_Pressure#6]
In 1-Pressure, while querying a pressure map for **CB620**, I am stopped by an error that refutes the values of the pam$pressure df:
```{r}
> pressure_maps <- geopressure_map(pam_short$pressure,
+   extent = c(gpr$extent_N, gpr$extent_W, gpr$extent_S, gpr$extent_E),
+   scale = gpr$map_scale,
+   max_sample = gpr$map_max_sample,
+   margin = gpr$map_margin
+ )
Error in geopressure_map(pam_short$pressure, extent = c(gpr$extent_N,  : 
  Pressure observation should be between 250 hPa (~10000m)  and 1100 hPa (sea level at 1013hPa). Check unit return by `pam_read()`
```

The structure of pam_short$pressure is the exact same as the rest of the tags that have passed through fine, and the values are in the proper range. Why is this?

**Comment by Rafnuss** [comment]
There is one data point at 1319hPa (end of may) that you need to mark as outliar in trainset:
![image](https://user-images.githubusercontent.com/7571260/188999843-08d13f23-443e-4a9a-956e-aef16ad94500.png)
