### ISSUE TITLE
Are barometric geolocators available for purchase? If so, how can one acquire them?

### ISSUE THREAD

**Issue by Yun-Tianming** [grhyne/SWWA_Pressure#9]

**Comment by grhyne** [comment]
Yes they are sold as multi-sensor geolocators either through Migrate Technology or Swiss Ornithological Institute. See recent publication for further information: https://doi.org/10.1093/ornithology/ukae010

**Comment by Yun-Tianming** [comment]
> Yes they are sold as multi-sensor geolocators either through Migrate Technology or Swiss Ornithological Institute. See recent publication for further information: https://doi.org/10.1093/ornithology/ukae010

THANKS!!
